name: 'Generation Comments'
description: 'Generates and posts comments on pull requests using OpenAI GPT-3.5'
inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  openai-api-key:
    description: 'OpenAI API Key'
    required: true
  prompt:
    description: 'Custom prompt for GPT-3.5'
    required: true
    default: 'このプルリクエストを分析し、簡潔にコメントを返します。'
runs:
  using: 'node20'
  main: './dist/index.js'
